### PR TITLE
Run optimize and vacuum operations after updating file-registry

### PR DESCRIPTION
**Pull request by ekstromchristian**
### Description

Run optimize and vacuum operations after updating file-registry

### Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added **tests** that prove my fix is effective or that my feature works
- [ ] I have added necessary **documentation** (if appropriate)
- [x] I have updated the **CHANGELOG.md**

### CODE REVIEW

**Comment by bulv1ne** [comment]
Should we really run optimize and vacuum every time we update a file_registry delta table? Shouldn’t that instead be done separate on a different schedule like (bi-)weekly?

Then again I don’t know how to do this easier. What are your thoughts @ownbite

**Comment by ownbite** [comment]
It is easier to maintain if we do it every time we trigger the lift job. Tough how much longer does it take to run the optimize and vacuum vs not running it?

If the cluster needs to be up for another 5 minutes each run  because of vacuum and optimize then maybe we should have a look at the  (bi-)weekly schedule.

@ekstromchristian could you do one or two tests on how long the two operations take?

**Comment by ekstromchristian** [comment]
The time to do a optimize and vacuum varies a lot. It depends on when it was last performed and the size of the table.
https://husqvarnagroup.cloud.databricks.com/#notebook/138601/command/138611
Optimize is 4 seconds up to 4.2 minutes for a larger table if it has been a couple of days since last time.
Vacuum is faster, 3-13 seconds. 

I think we actually should do this every time.

The other option is to schedule this optimize and vacuum notebook to run daily or every other day

**Comment by ownbite** [comment]
In that case lets run it every time

**Review by ownbite — APPROVED** [review]

**Review by bulv1ne — APPROVED** [review]
Good enough :+1:

**Pull request merged**
